Added separate scans for normal and hidden truecrypt volume lookups
TrueCrypt4 seems to have a bug: Sometimes the hidden header seems to get
overwritten for no apparent cause.

I'm afraid it might get overwritten with normal user data in that case,
so it seems unwise to restore the (unused) hidden header in such cases,
because that would overwrite the user data as well.

The current TC Volume Lookup code uses a checksum of both the normal
and the hidden header in order to identifiy a volume. If the hidden
header becomes overwritten, the header lookup will be unable to match
the volume.

Therefore, the new script works in two phases: First, it only tries to
match the normal headers. If no match was found, a second pass will be
run matching the hidden headers only.

This should work with all normal volumes, and also with those hidden
volumes where the hidden headers have not been damaged.

Another change of this commit is the xauth "stealer" script. It now
supports to import the "stolen" authority not only to the current user,
but also to specific different user. The default destination is still
the current user, though.

diff --git a/steal-xauth-from-user b/steal-xauth-from-user
--- a/steal-xauth-from-user
+++ b/steal-xauth-from-user
@@ -1,6 +1,6 @@
 #! /bin/sh
 # Allows root to steal the X authorization cookie from a specified user.
-# Written in 2007 by Guenther Brunthaler.
+# Written 2007 - 2011 by Guenther Brunthaler.
 
 
 die() {
@@ -9,12 +9,31 @@ die() {
 }
 
 
-USERNAME=${1?Usage $0 <username>}
-USERHOME=`awk -F: '$1 == "'$USERNAME'" {print $6}' < /etc/passwd`
-if test -z "$USERHOME" || test ! -d "$USERHOME"; then
-	die "Invalid user!"
-fi
+gethome() {
+	LC_ALL=C USERHOME=`awk -F: '$1 == "'$1'" {print $6}' < /etc/passwd`
+	if
+		test -z "$USERHOME" || test ! -d "$USERHOME"
+	then
+		die "Invalid user '$1'!"
+	fi
+}
+
+
+USERNAME0=${1?Usage $0 <username> [ <receiving_user> ]}
+gethome "$USERNAME0"; USERHOME0=$USERHOME
+USERNAME=${2:-root}
+gethome "$USERNAME"
 unset XAUTHORITY
-xauth -f "$USERHOME"/.Xauthority extract - "$DISPLAY" | xauth merge - \
-	|| die "Could not import user $USERNAME's xauth cookie!"
-echo "Xauth cookie from user $USERNAME has been imported successfully!"
+XA0="$USERHOME0"/.Xauthority
+XA="$USERHOME"/.Xauthority
+test -f "$XA0" || die "Could not find authority database '$XA0'!"
+if
+	test '!' -e "$XA"
+then
+	touch "$XA" || die "Could not create authority database '$XA'!"
+fi
+xauth -f "$XA0" extract - "$DISPLAY" | xauth -f "$XA" merge - \
+	|| die "Could not import user $USERNAME0's xauth cookie!"
+chown "$USERNAME:$USERMAME" "$XA" || die "chown failed for '$XA'!"
+echo "Xauth cookie from user $USERNAME0 has been imported successfully"
+echo "for user $USERNAME!"
